package com.example.util

object AppStrings {

    fun get(key: Key, isGujarati: Boolean): String {
        return if (isGujarati) key.gu else key.en
    }

    enum class Key(val gu: String, val en: String) {
        APP_NAME("મંત્ર જપ", "Mantra Jap"),
        TAGLINE("મંત્ર જપ કરો, મનને શાંતિ આપો", "Chant Mantras, Find Inner Peace"),
        TODAY_JAPA("આજનો જપ", "Today's Japa"),
        START_JAPA("જપ શરૂ કરો", "Start Japa"),
        MY_MANTRAS("મારા મંત્ર", "My Mantras"),
        JAPA_HISTORY("જપ ઇતિહાસ", "Japa History"),
        STATISTICS("આંકડા", "Statistics"),
        SETTINGS("સેટિંગ્સ", "Settings"),
        HOME("હોમ", "Home"),
        QUICK_MANTRAS("ઝડપી મંત્ર", "Quick Mantras"),
        TODAY_COUNT("આજનો કુલ જપ", "Today's Count"),
        DAILY_GOAL("આજનો લક્ષ્ય", "Daily Goal"),
        MALA_ROUNDS("માળા", "Mala Rounds"),
        STREAK("દિવસ સળંગ જપ", "Day Streak"),
        TAP_TO_CHANT("જપ કરો", "TAP TO CHANT"),
        PAUSE("થોભો", "Pause"),
        RESUME("ચાલુ કરો", "Resume"),
        UNDO("પાછળ", "Undo"),
        RESET("રીસેટ", "Reset"),
        SAVE("સાચવો", "Save"),
        FINISH("પૂર્ણ", "Finish"),
        TARGET_REACHED("જપ પૂર્ણ 🙏", "Japa Completed 🙏"),
        PEACE_MANTRA("ૐ શાંતિઃ શાંતિઃ શાંતિઃ", "Om Shanti Shanti Shanti"),
        CHANT_AGAIN("ફરી જપ કરો", "Chant Again"),
        ANOTHER_MANTRA("બીજો મંત્ર પસંદ કરો", "Select Another Mantra"),
        GO_HOME("હોમ પર જાઓ", "Go to Home"),
        COMPLETED_COUNT("પૂર્ણ થયેલ જપ", "Completed Chants"),
        DURATION("સમયગાળો", "Duration"),
        SECONDS("સેકન્ડ", "sec"),
        MINUTES("મિનિટ", "min"),
        ADD_MANTRA("નવો મંત્ર ઉમેરો", "Add New Mantra"),
        EDIT_MANTRA("મંત્ર સુધારો", "Edit Mantra"),
        MANTRA_NAME("મંત્રનું નામ", "Mantra Name"),
        TRANSLITERATION("ઉચ્ચાર / ટૂંકી ઓળખ", "Transliteration / Short info"),
        MEANING("અર્થ / માહાત્મ્ય", "Meaning / Significance"),
        DEITY("ભગવાન / દેવી", "Deity"),
        SAVE_MANTRA("સાચવો", "Save Mantra"),
        CANCEL("રદ કરો", "Cancel"),
        DELETE("કાઢી નાખો", "Delete"),
        CONFIRM_DELETE("શું તમે આ મંત્ર કાઢી નાખવા માંગો છો?", "Do you want to delete this mantra?"),
        FAVORITES_ONLY("પસંદગીના મંત્ર", "Favorites Only"),
        ALL_MANTRAS("બધા મંત્ર", "All Mantras"),
        FILTER_TODAY("આજે", "Today"),
        FILTER_YESTERDAY("ગઈકાલે", "Yesterday"),
        FILTER_WEEK("આ અઠવાડિયે", "This Week"),
        FILTER_MONTH("આ મહિને", "This Month"),
        FILTER_ALL("બધું", "All"),
        CLEAR_HISTORY("ઇતિહાસ સાફ કરો", "Clear History"),
        CONFIRM_CLEAR_HISTORY("શું તમે ખરેખર તમામ જપ ઇતિહાસ કાઢી નાખવા માંગો છો?", "Are you sure you want to delete all japa history?"),
        NO_HISTORY("કોઈ જપ ઇતિહાસ મળ્યો નથી", "No japa history yet"),
        NO_HISTORY_DESC("શાંત મનથી જપ શરૂ કરો, અહીં તમારો ઇતિહાસ દેખાશે.", "Start chanting with a calm mind, your history will appear here."),
        TOTAL_LIFETIME("આજીવન કુલ જપ", "Lifetime Total Japa"),
        TOTAL_7_DAYS("છેલ્લા ૭ દિવસનો જપ", "Last 7 Days Total"),
        TOTAL_30_DAYS("છેલ્લા ૩૦ દિવસનો જપ", "Last 30 Days Total"),
        TOTAL_ROUNDS("કુલ પૂર્ણ કરેલ ૧૦૮ માળા", "Total 108 Malas Done"),
        MOST_USED_MANTRA("સૌથી વધુ જપ કરેલ મંત્ર", "Most Chanted Mantra"),
        CURRENT_STREAK("હાલનો સળંગ જપ", "Current Streak"),
        LONGEST_STREAK("સૌથી લાંબો સળંગ જપ", "Longest Streak"),
        DAYS("દિવસ", "Days"),
        TIMES("વખત", "times"),
        LANGUAGE("ભાષા / Language", "Language"),
        THEME("થીમ", "Theme"),
        THEME_SYSTEM("સિસ્ટમ મુજબ", "System Default"),
        THEME_LIGHT("લાઈટ (દિવસ)", "Light Mode"),
        THEME_DARK("ડાર્ક (રાત)", "Dark Mode"),
        HAPTIC_FEEDBACK("કંપન (વાઇબ્રેશન)", "Haptic Vibration"),
        SOUND_FEEDBACK("જપ અવાજ", "Chant Sound"),
        KEEP_SCREEN_AWAKE("સ્ક્રીન ચાલુ રાખો", "Keep Screen Awake"),
        DEFAULT_TARGET("મૂળભૂત જપ લક્ષ્ય", "Default Japa Target"),
        RESET_ALL_DATA("તમામ ડેટા રીસેટ કરો", "Reset All Data"),
        CONFIRM_RESET_ALL("આનાથી તમામ ઇતિહાસ અને ઉમેરેલા મંત્રો ભૂંસાઈ જશે. શું આગળ વધવું છે?", "This will reset all history, settings and custom mantras. Continue?"),
        PRIVACY_POLICY("ગોપનીયતા નીતિ", "Privacy Policy"),
        PRIVACY_DESC("આ એપ્લિકેશન ૧૦૦% ઑફલાઇન છે. કોઈ એકાઉન્ટ કે લોગિનની જરૂર નથી. તમારો તમામ ડેટા ફક્ત તમારા ફોનમાં જ સુરક્ષિત રહે છે. કોઈ વ્યક્તિગત માહિતી ક્યાંય મોકલવામાં આવતી નથી.", "This app is 100% offline. No account or login required. All your chanting data stays strictly private on your device."),
        ABOUT("એપ વિશે", "About App"),
        ABOUT_DESC("મંત્ર જપ એ હિન્દુ ધર્મના પવિત્ર મંત્રોના જપ અને માળા ગણતરી માટે સરળ, સુંદર અને જાહેરાત મુક્ત એપ્લિકેશન છે.", "Mantra Jap is a serene, offline, ad-free Hindu mantra chanting and japa counter app."),
        ONBOARDING_WELCOME("જય શ્રી કૃષ્ણ 🙏", "Welcome 🙏"),
        ONBOARDING_SUBTITLE("મંત્ર જપમાં આપનું હાર્દિક સ્વાગત છે", "Welcome to Mantra Jap"),
        ONBOARDING_FEATURE_1("પવિત્ર મંત્ર જપ અને માળા ગણતરી (૧૧, ૨૧, ૫૪, ૧૦૮, ૧૦૦૮)", "Sacred Mantra Japa & Mala Counter (11, 21, 54, 108, 1008)"),
        ONBOARDING_FEATURE_2("સંપૂર્ણ ઑફલાઇન - ઇન્ટરનેટ વગર ચાલે છે", "Completely Offline - Works without internet"),
        ONBOARDING_FEATURE_3("કોઈ જાહેરાત નહીં - શાંત અને ભક્તિમય વાતાવરણ", "100% Ad-Free - Pure spiritual peace"),
        ONBOARDING_FEATURE_4("વડીલો માટે મોટા બટન અને સ્પષ્ટ અક્ષરો", "Elderly-friendly large buttons and clear text"),
        GET_STARTED("શરૂ કરો", "Get Started"),
        TARGET_LABEL("લક્ષ્ય:", "Target:"),
        ROUNDS_LABEL("માળા:", "Mala:"),
        CHOOSE_MANTRA("મંત્ર પસંદ કરો", "Select Mantra")
    }
}
